version: '3'

services:

  cloud-weather-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=cloud_weather_dev
      - POSTGRES_USER=cloud_weather_dev
      - POSTGRES_PASSWORD=cloud_weather_dev
    ports:
      - 5435:5432
    expose:
      - "5435"
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
